name = "flayve"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://final-6fd.pages.dev"
API_URL = "https://final-6fd.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "flayve-db-prod"
database_id = "c4b69158-bfed-4e21-ba98-7ceffe1e764b"

[[r2_buckets]]
binding = "R2"
bucket_name = "flayve-assets"