name = "flayve"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://flayve.com"
API_URL = "https://flayve.com"

[[d1_databases]]
binding = "DB"
database_name = "flayve-db-prod"
database_id = "7d53c054-b4b3-4739-8702-41eaa3da56bc"

[[r2_buckets]]
binding = "R2"
bucket_name = "flayve-assets"
